### ISSUE TITLE
Always using telephoto lens

### ISSUE THREAD

**Issue by D3S0X** [MSF-Jarvis/op5cam#2]
I use a OnePlus 5 with AICP Custom rom. I noticed that your camera Port is always using the telephoto lens. Also Auto hdr is not working and 1080p60 is not there

**Comment by MSF-Jarvis** [comment]
This port requires siankatabg's modifications to the framework to work perfectly. No way around it.

**Comment by MSF-Jarvis** [comment]
You'll need to rebuild the ROM with the last 7 commits from [here](https://github.com/siankatabg/android_frameworks_base/commits/OP5-CAMERA)

**Comment by D3S0X** [comment]
Oh okey i got no idea how to build a rom :o
So the rom developers need to do this, right?
Do i need to tell them or do you thing they'll do it "automatically"

**Comment by MSF-Jarvis** [comment]
Yes your ROM developer needs to implement this. You'll have to ask them to build the ROM with these commits.
